title: Blog by Jesús María Escudero Justel
description: This is a place in which I place some (hopefully) useful content
author: Jesús María Escudero Justel
url: "https://jmescuderojustel.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username:  jmescuderojustel
github_username:  artisau

# Post settings
permalink: /:year/:month/:day/:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jesús María Escudero Justel"