title: Blog by Jesús María Escudero Justel
description: This is a place in which I place some (hopefully) useful content about software development and all the things that are related to it (not everything is coding)
author: Jesús María Escudero Justel
show_downloads: false

# Build settings
markdown: kramdown
theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Social links
github_username:  jmescuderojustel
github_username:  artisau

# Post settings
permalink: /:year/:month/:day/:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jesús María Escudero Justel"